baseURL = "https://blog.eleutherai.github.io/"
languageCode = "en-us"
title = "Eleuther AI Blog"
theme = "eai-theme"
contentDir = "content-blog"
publishDir="public-blog"
[params]
    logo="EleutherAI"
    logo_image_url="images/eai_logo.png"
    contact_mail="contact@eleuther.ai"
    site_type="blog"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Get Involved"
    url = "/get-involved/"
    weight = 5
