baseURL = "https://eleuther.ai/"
languageName = "English"
languageCode = "en-us"
title = "EleutherAI"
theme = "eai-theme"
contentDir = "content"
publishDir = "public"
[params]
    logo="EleutherAI"
    promo_text = "A grassroots collective of researchers working to open source AI research."
    logo_image_url="images/eai_logo.png"
    meta_image="images/meta_image.jpg"
    contact_mail="contact@eleuther.ai"
    site_type="website"
    sitename = "EleutherAI"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "solarized-light"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "https://blog.eleuther.ai"
    weight = 4
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 5
  [[menu.main]]
    name = "Get Involved"
    url = "/get-involved/"
    weight = 6